AutoRepairParts/urls.py
"""
Definition of urls for AutoRepairParts.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
#from app.forms import AutoCompleteView
# admin.autodiscover()

urlpatterns = [
    # Examples:
    url(
        r'^favicon.ico$',
        RedirectView.as_view(
            url=staticfiles_storage.url('app/images/favicon.ico'),
            permanent=False),
        name="favicon"
    ),
    url(r'^api/get_parts/', app.views.get_parts, name='get_parts'),
    url(r'^api/get_customers/', app.views.get_customers, name='get_customers'),
    url(r'^$', app.views.home, name='home'),
    url(r'^startInvoice$', app.views.startInvoice, name='startInvoice'),
    url(r'^updateInvoice/(?P<pk>\d+)$', app.views.updateInvoice, name='updateInvoice'),
    url(r'^invoice/(?P<pk>\d+)$', app.views.invoice, name='invoice'),

    url(r'^CustomerBills/(?P<customerID>\d+)$', app.views.customerBills, name='customerBills'),
    url(r'^TotalBills$', app.views.totalBills, name='totalBills'),
    url(r'^PaidBills$', app.views.paidBills, name='paidBills'),
    url(r'^PendingBills$', app.views.pendingBills, name='pendingBills'),
    url(r'^report$', app.views.report, name='report'),
    url(r'^customers$', app.views.customers, name='customers'),
    url(r'^parts/', include('app.urls', namespace="app")),

    url(r'^labours$', app.views.labour_list, name='labours'),
    url(r'^labour_create$', app.views.labour_create, name='labour_create'),
    url(r'^labour_update/(?P<pk>\d+)$', app.views.labour_update, name='labour_update'),
    url(r'^labour_delete/(?P<pk>\d+)$', app.views.labour_delete, name='labour_delete'),

    url(r'^export/xls/(?P<date>\d{4}-\d{2}-\d{2})/$', app.views.export_report_csv, name='export_report_csv'),
    url(r'^sendEmail$', app.views.sendEmail, name='sendEmail'),
    
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Login',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
]

app/urls.py
from django.conf.urls import url
from django.contrib import admin
from app import views

urlpatterns = [
    url(r'^$', views.part_list, name='parts'),
    url(r'^new$', views.part_create, name='part_new'),
    url(r'^edit/(?P<pk>\d+)$', views.part_update, name='part_edit'),
    url(r'^delete/(?P<pk>\d+)$', views.part_delete, name='part_delete'),
]

app/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
from django.core.validators import MinValueValidator, MaxValueValidator

class Part(models.Model):
    part_no = models.CharField(max_length=200)
    part_name = models.CharField(max_length=200)
    itemType = models.IntegerField()
    price = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    stock = models.PositiveIntegerField(default=0, blank=True)
    date_created = models.DateTimeField(default=datetime.now, blank=True)
    date_modified = models.DateTimeField(default=datetime.now, blank=True)

class Customer(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    contact = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    date_created = models.DateTimeField(default=datetime.now, blank=True)
    date_modified = models.DateTimeField(default=datetime.now, blank=True)

class Invoice(models.Model):
    invoiceNo = models.CharField(max_length=10, blank=True)
    customer = models.ForeignKey(Customer, null=True)
    plate = models.CharField(max_length=20)
    model = models.CharField(max_length=20)
    AC_CHOICES = ((True, 'AC'), (False, 'Non AC'))
    isAC = models.BooleanField(choices=AC_CHOICES, default='AC')
    Tran_CHOICES = ((True, 'Automatic'), (False, 'Manual'))
    transmission = models.BooleanField(choices=Tran_CHOICES, default='Automatic')
    color = models.CharField(max_length=20)
    miles = models.CharField(max_length=20)
    motor = models.CharField(max_length=20)
    year = models.CharField(max_length=20)
    partTotal = models.PositiveIntegerField(default = 0)
    labourTotal = models.PositiveIntegerField(default = 0)
    taxAmount = models.DecimalField(default = 0, max_digits=10, decimal_places=2)
    totalAmount = models.DecimalField(default = 0, validators=[MinValueValidator(0)], max_digits=10, decimal_places=2)
    discount = models.PositiveIntegerField(default = 0, validators=[MaxValueValidator(100)])
    grandTotal = models.PositiveIntegerField()
    paid = models.PositiveIntegerField()
    balance = models.IntegerField()
    status = models.BooleanField()
    due_date = models.DateField(default=datetime.now)
    date_created = models.DateTimeField(default=datetime.now, blank=True)
    date_modified = models.DateTimeField(default=datetime.now, blank=True)

class InvoiceItems(models.Model):
    invoice = models.ForeignKey(Invoice, null=True)
    part = models.ForeignKey(Part)
    part_name = models.CharField(max_length=200)
    itemType = models.IntegerField()
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    amount = models.PositiveIntegerField()

app/templates/app/charts.html
{% extends "app/layout.html" %}
{% block content %}

    <div class="container-fluid">

          <!-- Area Chart Example-->
          <div class="card mb-3">
            <div class="card-header">
              <i class="fas fa-chart-area"></i>
              Sales</div>
            <div class="card-body">
              <canvas id="myAreaChart" width="100%" height="30"></canvas>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-8">
              <div class="card mb-3">
                <div class="card-header">
                  <i class="fas fa-chart-bar"></i>
                  Sales</div>
                <div class="card-body">
                  <canvas id="myBarChart" width="100%" height="50"></canvas>
                </div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="card mb-3">
                <div class="card-header">
                  <i class="fas fa-chart-pie"></i>
                  Bills
                </div>
                <div class="card-body">
                  <canvas id="myPieChart" width="100%" height="100"></canvas>
                </div>
              </div>
            </div>
          </div>

    </div>
    <!-- /.container-fluid -->

{% endblock %}

app/templates/app/customer.html
{% extends "app/layout.html" %}
{% block content %}
{% load widget_tweaks %}
    <div class="container-fluid">

        <!-- DataTables Example -->
        <div class="card mb-3">
            <div class="card-header form-row">
                <span><i class="fas fa-fw fa-users"></i> Customers </span>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    {% if customers %}
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Address</th>
                                <th>Contact</th>
                                <th>Email</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Name</th>
                                <th>Address</th>
                                <th>Contact</th>
                                <th>Email</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            {% for customer in customers %}
                            <tr>
                                <td>{{customer.name}}</td>
                                <td>{{customer.address}}</td>
                                <td>{{customer.contact}}</td>
                                <td>{{customer.email}}</td>
                                <td>
                                    <a href="{% url 'customerBills' customer.id %}" class="btn btn-success btn-sm">
                                        <i class="fas fa-money-bill-alt"></i> Bills
                                    </a>
                                </td>
                            </tr>

                            {% endfor %}
                        </tbody>
                    </table>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
{% endblock %}

app/templates/app/labour.html
{% extends "app/layout.html" %}
{% block content %}
{% load widget_tweaks %}
<div class="container-fluid">
    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header form-row">
            <span><i class="fas fa-fw fa-dollar-sign"></i> Labours </span>
            <div class="ml-auto mr-0 mr-md-3 my-2 my-md-0">
                <a href="" data-toggle="modal" data-target="#addpart" class="btn btn-primary add-btn btn-sm">
                    <i class="fa fa-plus"></i> Add New
                </a>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                {% if part_list %}
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Labour Name</th>
                            <th width="8%">Price</th>
                            <th width="16%">Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Labour Name</th>
                            <th>Price</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for part in part_list %}
                        <tr>
                            <td>{{part.part_name}}</td>
                            <td>{{part.price}}</td>
                            <td>
                                <a href="" data-toggle="modal" data-target="#editpart{{part.id}}" class="btn btn-success btn-sm">
                                    <i class="fas fa-pencil-alt"></i> Edit
                                </a>
                                <a href="" data-toggle="modal" data-target="#delete{{part.id}}" class="btn btn-danger btn-sm">
                                    <i class="fas fa-trash-alt"></i> Delete
                                </a>
                            </td>
                        </tr>

                        <!-- Delete Modal-->
                        <div class="modal fade" id="delete{{part.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="card-header">
                                    <strong>Ready to Delete?</strong>
                                     <a href="" class="close btn btn-danger btn-sm" data-dismiss="modal">
                                        <i class="fas fa-times"></i>
                                    </a>
                                </div> 
                                <div class="modal-body"><h5>Are you sure you want to delete this item?</h5></div>
                                    <div class="modal-footer">
                                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                                    <form action="{% url 'labour_delete' part.id %}" method="POST">
                                        {% csrf_token %}
                                        <input type="submit" value="Delete" class="btn btn-primary" href=""/>
                                    </form>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- update Modal-->
                        <div class="modal fade" id="editpart{{part.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="card-header"><strong>Update Labour</strong>
                                    <a href="" class="close btn btn-danger btn-sm" data-dismiss="modal">
                                        <i class="fas fa-times"></i>
                                    </a>
                                </div>
                                <div class="modal-body">
                                    <div class="container">
                                        <div class="card card-register mx-auto mt-0">
                                            <div class="card-body">
                                                <form action="{% url "labour_update" part.id %}" method="POST">
                                                    {% csrf_token %}
                                                    {% render_field form.itemType value=2 type="hidden" %}
                                                    {% render_field form.part_no value=0 type="hidden" %}
                                                    <div class="form-group">
                                                        <div class="row">
                                                            <label for="id_part_name" class="col-sm-3 control-label">Name</label>
                                                            <div class="col-sm-9">
                                                                {% render_field form.part_name class="form-control" value=part.part_name%}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-group">
                                                        <div class="row">
                                                            <label for="id_price" class="col-sm-3 control-label">Price</label>
                                                            <div class="col-sm-9">
                                                                {% render_field form.price class="form-control" value=part.price%}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <input type="hidden" name="next" value="/" />
                                                    <div class="text-right">
                                                        <input value="Submit" type="submit" class="btn btn-primary"/>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </div>
                        </div>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
            </div>
        </div>
    </div>

</div>
    <!-- /.container-fluid -->

    <!-- add Modal-->
    <div class="modal fade" id="addpart" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="card-header"><strong>Add New Labour</strong>
            <a href="" class="close btn btn-danger btn-sm" data-dismiss="modal">
                <i class="fas fa-times"></i>
            </a>
          </div>
          <div class="modal-body">
              <div class="container">
                  <div class="card card-register mx-auto mt-0">
                    <div class="card-body">
                      <form action="{% url 'labour_create' %}" method="POST">
                        {% csrf_token %}
                        {% render_field form.itemType value=2 type="hidden" %}
                        {% render_field form.part_no value=0 type="hidden" %}
                        <div class="form-group">
                          <div class="row">
                              <label for="id_part_name" class="col-sm-3 control-label">Name</label>
                              <div class="col-sm-9">
                                 {% render_field form.part_name class="form-control" %}
                              </div>
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="row">
                              <label for="id_price" class="col-sm-3 control-label">Price</label>
                              <div class="col-sm-9">
                                 {% render_field form.price class="form-control" %}
                              </div>
                          </div>
                        </div>
                        <input type="hidden" name="next" value="/" />
                        <div class="text-right">
                            <input value="Submit" type="submit" class="btn btn-primary"/>
                        </div>
                      </form>
                    </div>
                  </div>
              </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

app/templates/app/parts.html
{% extends "app/layout.html" %}
{% block content %}
{% load widget_tweaks %}
<div class="container-fluid">
    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header form-row">
            <span><i class="fas fa-truck-pickup"></i> Parts </span>
            <div class="ml-auto mr-0 mr-md-3 my-2 my-md-0">
                <a href="" data-toggle="modal" data-target="#addpart" class="btn btn-primary btn-sm">
                    <i class="fa fa-plus"></i> Add New
                </a>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                {% if part_list %}
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Part No</th>
                            <th>Part Name</th>
                            <th>Price</th>
                            <th>Stock</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th width="18%">Part No</th>
                            <th>Part Name</th>
                            <th width="8%">Price</th>
                            <th width="8%">Stock</th>
                            <th width="16%">Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for part in part_list %}
                        <tr>
                            <td>{{part.part_no}}</td>
                            <td>{{part.part_name}}</td>
                            <td>{{part.price}}</td>
                            <td>{{part.stock}}</td>
                            <td>
                                <a href="" data-toggle="modal" data-target="#editpart{{part.id}}" class="btn btn-success btn-sm">
                                    <i class="fas fa-pencil-alt"></i> Edit
                                </a>
                                <a href="" data-toggle="modal" data-target="#delete{{part.id}}" class="btn btn-danger btn-sm">
                                    <i class="fas fa-trash-alt"></i> Delete
                                </a>
                            </td>
                        </tr>

                        <!-- Delete Modal-->
                        <div class="modal fade" id="delete{{part.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="card-header">
                                    <strong>Ready to Delete?</strong>
                                     <a href="" class="close btn btn-danger btn-sm" data-dismiss="modal">
                                        <i class="fas fa-times"></i>
                                    </a>
                                </div> 
                                <div class="modal-body"><h5>Are you sure you want to delete this item?</h5></div>
                                <div class="modal-footer">
                                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                                    <form action="{% url 'app:part_delete' part.id %}" method="POST">
                                        {% csrf_token %}
                                        <input type="submit" value="Delete" class="btn btn-primary" href=""/>
                                    </form>
                                </div>
                            </div>
                            </div>
                        </div>

                        <!-- update Modal-->
                        <div class="modal fade" id="editpart{{part.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="card-header"><strong>Update Part</strong>
                                    <a href="" class="close btn btn-danger btn-sm" data-dismiss="modal">
                                        <i class="fas fa-times"></i>
                                    </a>
                                </div>
                                <div class="modal-body">
                                    <div class="container">
                                        <div class="card card-register mx-auto mt-0">
                                        <div class="card-body">
                                            <form action="{% url "app:part_edit" part.id %}" method="POST">
                                            {% csrf_token %}
                                            {% render_field form.itemType value=1 type="hidden" %}
                                            <div class="form-group">
                                                <div class="row">
                                                    <label for="id_part_no" class="col-sm-3 control-label">Part No</label>
                                                    <div class="col-sm-9">
                                                        {% render_field form.part_no class="form-control" value=part.part_no%}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="row">
                                                    <label for="id_part_name" class="col-sm-3 control-label">Part Name</label>
                                                    <div class="col-sm-9">
                                                        {% render_field form.part_name class="form-control" value=part.part_name%}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="row">
                                                    <label for="id_price" class="col-sm-3 control-label">Price</label>
                                                    <div class="col-sm-9">
                                                        {% render_field form.price class="form-control" value=part.price%}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="row">
                                                    <label for="id_stock" class="col-sm-3 control-label">Stock</label>
                                                    <div class="col-sm-9">
                                                        {% render_field form.stock class="form-control" value=part.stock%}
                                                    </div>
                                                </div>
                                            </div>
                                            <input type="hidden" name="next" value="/" />
                                            <div class="text-right">
                                                <input value="Submit" type="submit" class="btn btn-primary"/>
                                            </div>
                                            </form>
                                        </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </div>
                        </div>
                        {% endfor %}
                    </tbody>
                </table>
                {% endif %}
            </div>
        </div>
    </div>

</div>
    <!-- /.container-fluid -->

    <!-- add Modal-->
    <div class="modal fade" id="addpart" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="card-header"><strong>Add New Part</strong>
            <a href="" class="close btn btn-danger btn-sm" data-dismiss="modal">
                <i class="fas fa-times"></i>
            </a>
          </div>
          <div class="modal-body">
              <div class="container">
                  <div class="card card-register mx-auto mt-0">
                    <div class="card-body">
                      <form action="{% url 'app:part_new' %}" method="POST">
                        {% csrf_token %}
                        {% render_field form.itemType value=1 type="hidden" %}
                        <div class="form-group">
                          <div class="row">
                              <label for="id_part_no" class="col-sm-3 control-label">Part No</label>
                              <div class="col-sm-9">
                                  {% render_field form.part_no class="form-control" %}
                              </div>
                          </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="id_part_name" class="col-sm-3 control-label">Part Name</label>
                                <div class="col-sm-9">
                                    {% render_field form.part_name class="form-control" %}
                                </div>
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="row">
                              <label for="id_price" class="col-sm-3 control-label">Price</label>
                              <div class="col-sm-9">
                                  {% render_field form.price class="form-control" %}
                              </div>
                          </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="id_stock" class="col-sm-3 control-label">Stock</label>
                                <div class="col-sm-9">
                                    {% render_field form.stock class="form-control" %}
                                </div>
                            </div>
                        </div>
                        <input type="hidden" name="next" value="/" />
                        <div class="text-right">
                            <input value="Submit" type="submit" class="btn btn-primary"/>
                        </div>
                      </form>
                    </div>
                  </div>
              </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}